filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.labels.logging: "filebeat"
          config:
            - type: log
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
              json.keys_under_root: true

processors:
- dissect:
    tokenizer: "%{timestamp} %{+timestamp} %{level} [%{component}] %{message}\n"
    field: "log"
    target_prefix: "log_fields"
- drop_fields:
    fields: ["source","stream","processor","beat","host","prospector","input","time","docker.container.labels"]
    
output.elasticsearch:
  hosts: "elastic:9200"
  index: "filebeat"

setup.template.enabled: false
#setup.template.name: filebeat
#setup.template.pattern: "filebeat-*"

logging.metrics.enabled: false
